config/routes.rb
SystemsCheck7::Application.routes.draw do

  resources :buildings, only: [:new, :create, :index]
  resources :owners, only: [:new, :create, :destroy, :show, :index]

  root to: "buildings#index"

end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :owner

  validates :street_address,  presence: true
  validates :city,            presence: true, format: {with: /^[a-zA-Z\s]+$/, multiline: true}
  validates :state,           presence: true, format: {with: /^([Aa][LKSZRAEPlkszraep]|[Cc][AOTaot]|[Dd][ECec]|[Ff][LMlm]|[Gg][AUau]|HI|hi|[Ii][ADLNadln]|[Kk][SYsy]|LA|la|[Mm][ADEHINOPSTadehinopst]|[Nn][CDEHJMVYcdehjmvy]|[Oo][HKRhkr]|[Pp][ARWarw]|RI|ri|[Ss][CDcd]|[Tt][NXnx]|UT|ut|[Vv][AITait]|[Ww][AIVYaivy])$/,
                                                    message: "Two letter abreviations please" , multiline: true }
  validates :postal_code,     presence: true, format: {:with => /^\d{5}(-\d{4})?$/,
                                                    :message => "should be in the form 12345 or 12345-1234", multiline: true}


end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :buildings

  validates :first_name,    presence: true,   format: {with: /^[a-zA-Z]+$/, :multiline => true, message: "Please enter a valid first name"}
  validates :last_name,     presence: true,   format: {with: /^[a-zA-Z]+$/, :multiline => true, message: "Please enter a valid last name"}
  validates :email,         presence: true ,  :email => true

  def clean_up_buildings
    Building.where("owner_id = ?", id).update_all(:owner_id => nil)
  end

  def full_name
    first_name << " " << last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  def new
    @building = Building.new

  end

  def create
    @building = Building.new(building_params)

    if @building.save
        redirect_to new_building_path, notice: "New building created"
    else
      render 'new'
    end
  end

  def index
    @buildings = Building.all
  end

  protected
    def building_params
      params.require(:building).permit(:postal_code, :street_address, :state, :city, :description, :owner_id)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def index
    @owners = Owner.all
  end

  def destroy
    @owner = Owner.find(params[:id])
    @owner.clean_up_buildings

    @owner.delete
    redirect_to owners_url
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to new_owner_path, notice: "New owner created successfully"
    else
      render 'new'
    end
  end

protected

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :company)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/buildings/_new_form.html.erb
<%= simple_form_for @building do |f| %>
  <div class="row">
    <div class="small-12 medium-12 columns">
      <%= f.input :street_address,  required: true, placeholder: "4 Example Lane",  autofocus: true, label: "Street Address" %>
    </div>
    <div class="small-12 medium-4 columns">
      <%= f.input :city,            required: true, placeholder: "Boston"%>
    </div>
    <div class="small-12 medium-4 columns">
      <%= f.input :state,           required: true, placeholder: "MA"%>
    </div>
    <div class="small-12 medium-4 columns">
      <%= f.input :postal_code,     required: true, placeholder: "02129", label: "Postal Code" %>
    </div>
    <div class="small-12 medium-9 columns">
      <%= f.input :description, as: :text, placeholder: "Tell us about it" %>
    </div>
    <div class="small-12 medium-3 columns">
      <%= f.association :owner, label_method: :full_name, value_method: :id %>
    </div>
    <div class= "small-12 medium-12 columns">
     <%= f.submit "Create new Building" %>
    </div>
  </div>
<% end %>

app/views/buildings/index.html.erb
<table>
<tr>
  <td>address</td>
  <td>state</td>
  <td>town</td>
  <td>owner</td>

</tr>
<% @buildings.each do |building| %>
  <tr>
    <td><%= building.street_address %></td>
    <td><%= building.state %></td>
    <td><%= building.city %></td>
    <% if building.owner.nil? %>
      <td> </td>
    <% else %>
      <td><%=building.owner.full_name %></td>
    <% end %>
  </tr>
<% end %>

</table>

app/views/buildings/new.html.erb
<h1>Register a new building</h1>

<%= render 'new_form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
      <%= link_to "New Building", new_building_path %>
      <%= link_to "New Owner", new_owner_path %>
      <%= link_to "- All buildings -", buildings_path %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/owners/_new_owner.html.erb
<%= simple_form_for @owner do |f| %>
  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.input :first_name,      required: true, placeholder: "John",  autofocus: true %>
    </div>
    <div class="small-12 medium-6 columns">
      <%= f.input :last_name,      required: true, placeholder: "Smith"%>
    </div>
    <div class="small-12 medium-12 columns">
      <%= f.input :email,         required: true, placeholder: "jsmith@example.com"%>
    </div>
    <div class="small-12 medium-12 columns">
      <%= f.input :company,       placeholder: "Example Co" %>
    </div>
    <div class="small-12 medium-12 columns">
      <%= f.submit "Create new owner" %>
    </div>
  </div>

<% end %>

app/views/owners/index.html.erb
<table>
<tr>
  <td>address</td>
  <td>state</td>
  <td>town</td>
  <td>owner</td>
  <td>delete </td>

</tr>
<% @owners.each do |owner| %>
  <tr>
    <td><%= owner.first_name %></td>
    <td><%= owner.last_name %></td>
    <td><%= owner.email %></td>
    <td><%= owner.company.nil? ? "" : owner.company %></td>
    <td><%= link_to "Destroy #{owner.first_name}", owner, method: :delete %></td>
  </tr>
<% end %>

</table>

app/views/owners/new.html.erb
<h1>Register a new Owner</h1>

<%= render 'new_owner' %>